---
builds:
  - binary: terraform-checker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=static
    ldflags:
      - -s
      - -w
      - -X github.com/terraform-tools/terraform-checker/cmd.commit={{ .FullCommit }}
      - -X github.com/terraform-tools/terraform-checker/cmd.version={{ .Version }}
      - -X main.buildTime={{ .Date }}
      - -X main.buildRevision={{ .FullCommit }}
      - -X main.buildTag={{ .Version }}

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/terraform-tools/terraform-checker:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/terraform-tools/terraform-checker:{{ .Version }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: "ghcr.io/terraform-tools/terraform-checker:{{ .Version }}"
    image_templates:
      - "ghcr.io/terraform-tools/terraform-checker:{{ .Version }}-amd64"
      - "ghcr.io/terraform-tools/terraform-checker:{{ .Version }}-arm64v8"

snapshot:
  name_template: "{{ .FullCommit }}-SNAPSHOT"

release:
  github:
    owner: terraform-tools
    name: terraform-checker

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false
